version: "3.8"

services:
  app:
    image: wubdigitalinfo/workers:1.0
    container_name: docker-challenge-app
    ports:
      - "3000:3000"
    environment:
      - DB_URI=mongodb://mongo:27017/dockerChallengeDB
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:7
    container_name: docker-challenge-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
